"""empty message

Revision ID: 21ffa9a5f12
Revises: b8caef64c4
Create Date: 2015-06-06 05:59:20.832150

"""

# revision identifiers, used by Alembic.
revision = '21ffa9a5f12'
down_revision = 'b8caef64c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
