"""initial migration

Revision ID: 224d98025ef
Revises: None
Create Date: 2016-04-04 12:19:36.680490

"""

# revision identifiers, used by Alembic.
revision = '224d98025ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hide', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hide')
    ### end Alembic commands ###
