"""empty message

Revision ID: b8caef64c4
Revises: cd9d0c493b
Create Date: 2015-06-06 05:58:43.505023

"""

# revision identifiers, used by Alembic.
revision = 'b8caef64c4'
down_revision = 'cd9d0c493b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
