"""empty message

Revision ID: cd9d0c493b
Revises: None
Create Date: 2015-06-06 05:57:37.260270

"""

# revision identifiers, used by Alembic.
revision = 'cd9d0c493b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
